name: DurianPay CICD

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/durianpay

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Container
        run: |
          docker build -t $DOCKER_IMAGE:latest .

      - name: Tag & Push Develop Container
        if: github.event_name == 'push'
        run: |
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:develop
          docker push $DOCKER_IMAGE:develop

      - name: Tag & Push Production Container
        if: github.event_name == 'release'
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:production
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$TAG_NAME
          docker push $DOCKER_IMAGE:production
          docker push $DOCKER_IMAGE:$TAG_NAME

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        if: github.event_name == 'push'
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.SSH_HOST }} "echo 'SSH connection successful!'"