name: DurianPay CICD

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/durianpay

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the container
        run: |
          docker build -t $DOCKER_IMAGE:latest .

      - name: Tagging and push develop container
        if: github.event_name == 'push'
        run: |
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:develop
          docker push $DOCKER_IMAGE:develop

      - name: Tagging and push production container
        if: github.event_name == 'release'
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:production
          docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$TAG_NAME
          docker push $DOCKER_IMAGE:production
          docker push $DOCKER_IMAGE:$TAG_NAME
